In [2]:
### Kannan's numpy practice exercise....
import numpy as np

In [7]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
3.0
5.2


In [16]:
# NumPy can be used to create matrix called Arrays. Arrays can be two or more dimensions.
# A single dimensional array is called as Vector. Two or more dimensional arrays called matrix.
# Numpy allows necessary functionals to create, manipulate and store arrays.
# Vector can be created by convert a list into array
# Matrix is list of lists.

vec = np.array([1,2,3])
print(vec)
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n" + str(mat))
print("\n" + str(mat.T))

[1 2 3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
# you can create a numpy array using a range of numbers using arange() function. syntax Obj.arange(x,y,z)
# x is starting position that is inclusive
# y is ending position that is exclusive
# z is step size

vec2 = np.arange(0,20)
print(vec2)

vec3 = np.arange(3,21,6)
print("\n" + str(vec3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[ 3  9 15]


In [24]:
# in a Linear space is starting and ending point is inclusive unlike arange where ending point is exclusive. 
# reshape is used to convert an array to different dimensional array.

vec4 =  np.linspace(0,5,10)
print(vec4)
print("\n")
print("\n" + str(vec4.reshape(5,2)))
vec5 = vec4.reshape(5,2)
print("\n Vector 5 \n" + str(vec5))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]

 Vector 5 
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [29]:

# Obj.zeros(no of rows, no of colnms) functions create matrix with zeros 
mat2 = np.zeros([5,3])
print(mat2)

# Obj.ones(no of rows, no of colnms) functions create matrix with ones 
mat3 = np.ones([5,3])
print("\n")
print(mat3)

# Obj.eye(num) functions create matrix a square matrix of specified size and assigns one in identical row, columns  
mat5 = np.eye(5)
print("\n")
print(mat5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
# matrix manipulations


vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
vec7 = vec5 + vec6
print(vec7)

vec8 = vec5 * vec6
print(vec8)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [43]:
# matmul is a function that can be used to multiply matrices. syntax Obj.matmul(matrix1, matrix2)

print(mat)
print(vec)
product = np.matmul(mat,vec)
print(product)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[14 32 50]


In [52]:
#linalg can find 

print(np.linalg.solve(mat,product))
print()
print(np.linalg.inv(mat))

[-0.8  5.6  1.2]

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [53]:
# we can use numpy to generate samples of a rangdom variable

rand_mat = np.random.rand(5,5) #uniform random variable. uniform in value 0 and 1
rand_mat2= np.random.rand(10,5) #standard normal random variable. 
print()
print(rand_mat)
print()
print(rand_mat2)


[[0.16433538 0.33938759 0.0726224  0.72618158 0.58807746]
 [0.66973374 0.14170613 0.58518456 0.58542568 0.04524912]
 [0.87020396 0.81496854 0.54724045 0.82577974 0.76628234]
 [0.59642801 0.26325762 0.21442954 0.36111544 0.27849197]
 [0.02505578 0.70350378 0.50954495 0.19733136 0.48053009]]

[[0.00213951 0.47073049 0.29557193 0.60693861 0.43352348]
 [0.07526941 0.9439609  0.90138034 0.81082636 0.0813904 ]
 [0.99537633 0.8287587  0.75124876 0.70216498 0.28851989]
 [0.52080859 0.13843343 0.2519268  0.10589357 0.23661751]
 [0.21306224 0.04575106 0.43620673 0.15915527 0.66209495]
 [0.87571306 0.95876258 0.26987727 0.20189202 0.29723064]
 [0.32101703 0.89864308 0.80230469 0.48747222 0.07318361]
 [0.7313324  0.27798502 0.45654225 0.38986876 0.88163884]
 [0.4521782  0.15424784 0.17490217 0.65734386 0.89336302]
 [0.88048925 0.13322687 0.38921854 0.15990452 0.96269882]]


In [56]:
## numpy can be used to calculate mean and standard deviation
print(np.mean(rand_mat))
print(np.std(rand_mat2))

print("Min and Max")
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.4548826880240011
0.3075656441304473
Min and Max
0.025055776120267548
0.995376329584225


In [3]:
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 1.60349081  1.43905489  0.38812999 -1.07172555 -0.95207438  0.6700085
  0.92370682 -1.25453347 -0.07159513 -1.63712838  0.75192881  0.99270313
 -0.17939815 -0.42872661 -0.01328746 -0.64623978  0.10180735 -0.67669598
 -1.90705136]
0.9237068160789245


In [4]:
#accessing multiple entries at once using numpy array
print(rand_vec[4:9])

[-0.95207438  0.6700085   0.92370682 -1.25453347 -0.07159513]


In [16]:
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-5.         -0.69322551 -5.         -0.04822138 -0.83239137]


In [17]:
#randn function can be used to assign random float values in an array 
rand_mat = np.random.randn(5,5)
print(rand_mat)
print(rand_mat[3,2])
print(rand_mat[3][2])

[[ 1.42592024  0.97663832  0.31615884  1.4780667  -0.47079796]
 [ 1.9452025  -1.04159918  0.00236168  0.16778174  0.90414548]
 [ 0.14576987 -1.17819282 -0.33225465  1.21870442 -1.39103952]
 [ 0.26531893  0.66191332  0.57587937 -0.95761329  0.22252164]
 [-0.07503436  1.04952511  0.12322204 -0.54017143 -0.12063614]]
0.5758793743135224
0.5758793743135224


In [18]:
#slicing a matrix
print(rand_mat[0:3,3:5])
rand_mat[0:3,3:5] = 9
print()
print(rand_mat)
print()
rand_mat[0:3,3:5] = [[1,2],[3,4],[5,6]]
print()
print(rand_mat)

[[ 1.4780667  -0.47079796]
 [ 0.16778174  0.90414548]
 [ 1.21870442 -1.39103952]]

[[ 1.42592024e+00  9.76638321e-01  3.16158840e-01  9.00000000e+00
   9.00000000e+00]
 [ 1.94520250e+00 -1.04159918e+00  2.36168049e-03  9.00000000e+00
   9.00000000e+00]
 [ 1.45769869e-01 -1.17819282e+00 -3.32254646e-01  9.00000000e+00
   9.00000000e+00]
 [ 2.65318930e-01  6.61913320e-01  5.75879374e-01 -9.57613293e-01
   2.22521642e-01]
 [-7.50343623e-02  1.04952511e+00  1.23222042e-01 -5.40171427e-01
  -1.20636142e-01]]


[[ 1.42592024e+00  9.76638321e-01  3.16158840e-01  1.00000000e+00
   2.00000000e+00]
 [ 1.94520250e+00 -1.04159918e+00  2.36168049e-03  3.00000000e+00
   4.00000000e+00]
 [ 1.45769869e-01 -1.17819282e+00 -3.32254646e-01  5.00000000e+00
   6.00000000e+00]
 [ 2.65318930e-01  6.61913320e-01  5.75879374e-01 -9.57613293e-01
   2.22521642e-01]
 [-7.50343623e-02  1.04952511e+00  1.23222042e-01 -5.40171427e-01
  -1.20636142e-01]]


In [19]:
# creating a matrix from another matrix. IF new matrix value is changes, then the original matrix also changes. 
# this is like the pointers in C or C++ where the new value actually linked to the original value.
# In order to ensure that the original values doesnt get changed, use copy() function

print(rand_mat)
sub_mat = rand_mat[0:3,3:5].copy()
print(sub_mat)
sub_mat[:] = 7
print(sub_mat)
print(rand_mat)

[[ 1.42592024e+00  9.76638321e-01  3.16158840e-01  1.00000000e+00
   2.00000000e+00]
 [ 1.94520250e+00 -1.04159918e+00  2.36168049e-03  3.00000000e+00
   4.00000000e+00]
 [ 1.45769869e-01 -1.17819282e+00 -3.32254646e-01  5.00000000e+00
   6.00000000e+00]
 [ 2.65318930e-01  6.61913320e-01  5.75879374e-01 -9.57613293e-01
   2.22521642e-01]
 [-7.50343623e-02  1.04952511e+00  1.23222042e-01 -5.40171427e-01
  -1.20636142e-01]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[7. 7.]
 [7. 7.]
 [7. 7.]]
[[ 1.42592024e+00  9.76638321e-01  3.16158840e-01  1.00000000e+00
   2.00000000e+00]
 [ 1.94520250e+00 -1.04159918e+00  2.36168049e-03  3.00000000e+00
   4.00000000e+00]
 [ 1.45769869e-01 -1.17819282e+00 -3.32254646e-01  5.00000000e+00
   6.00000000e+00]
 [ 2.65318930e-01  6.61913320e-01  5.75879374e-01 -9.57613293e-01
   2.22521642e-01]
 [-7.50343623e-02  1.04952511e+00  1.23222042e-01 -5.40171427e-01
  -1.20636142e-01]]


In [28]:
rand_vec = np.random.randn(15)
print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])
rand_vec[rand_vec>.5] = -5
print(rand_vec)
np.save("Rand_vec", rand_vec) #save() stores single numpy array
load_vec = np.load('rand_vec.npy')
print("\nLoaded vector....\n")
print(load_vec)
np.savez("zip_data", rand_vec=rand_vec, rand_mat=rand_mat)
load_zip = np.load('zip_data.npz')
print("\n Loaded zipped random vector \n")
print(load_zip['rand_vec'])

print("\n Loaded zipped random matrix \n")
print(load_zip['rand_mat'])

np.savetxt("rand_vector.txt",rand_vec, delimiter=",")
rand_vec_txt = np.loadtxt("rand_vector.txt")
print("\n Random Vector Text \n" + str(rand_vec_txt))

[-0.54981607 -1.90803004  1.34061818 -0.47522279  1.1937306  -0.49331225
 -0.59896834  0.59085431  0.19041415  0.26396739  0.54531573  0.46551564
  0.41685042 -1.2782901  -0.46540817]
[False False  True False  True False False  True  True  True  True  True
  True False False]
[1.34061818 1.1937306  0.59085431 0.19041415 0.26396739 0.54531573
 0.46551564 0.41685042]
[-0.54981607 -1.90803004 -5.         -0.47522279 -5.         -0.49331225
 -0.59896834 -5.          0.19041415  0.26396739 -5.          0.46551564
  0.41685042 -1.2782901  -0.46540817]

Loaded vector....

[-0.54981607 -1.90803004 -5.         -0.47522279 -5.         -0.49331225
 -0.59896834 -5.          0.19041415  0.26396739 -5.          0.46551564
  0.41685042 -1.2782901  -0.46540817]

 Loaded zipped random vector 

[-0.54981607 -1.90803004 -5.         -0.47522279 -5.         -0.49331225
 -0.59896834 -5.          0.19041415  0.26396739 -5.          0.46551564
  0.41685042 -1.2782901  -0.46540817]

 Loaded zipped random matri